### ISSUE TITLE
The form not work with wp api v2

### ISSUE THREAD

**Issue by jairgarcia** [tlovett1/custom-contact-forms#274]
How make work with wp api v2.

Thanks.

**Comment by michaelnagy** [comment]
+1

**Comment by michaelnagy** [comment]
I can't find any documentation on how to use it with WP-API, howhever the plugin is listed in the Official WP-API list of compatible plugins.

**Comment by tlovett1** [comment]
I've used with V2 of the API. In fact the plugin bundles it. What errors are happening exactly?

**Comment by beatelite** [comment]
Is there any documentation to use this with the API?

I'd love to create and manage forms using an endpoint. Hope that's what is possible here.

**Comment by jairgarcia** [comment]
@tlovett1 I don't add a new form in wordpress, see the follow link: http://prntscr.com/buvnm7

I use AngularJs with WP-API v2, any ideas?

Thanks

**Comment by beatelite** [comment]
@jairgarcia I use angular and wp api as well. Let me know if you figure it out as I'm going to dig into this next week. If I find anything out, I'll let you know as well.

**Comment by pabloacastillo** [comment]
When i disable the WP-API v2 the forms work again, this is the error i get from the Chrome Console:
`
Uncaught TypeError: Cannot read property 'raw' of undefined
source:http://xxxxxxxxxxxxxx/wp-admin/post.php?post=3633&action=edit
line:6
`

**Comment by pabloacastillo** [comment]
When i try to create a form from inside the plugin i get:

`
Uncaught ReferenceError: content is not defined
source:http://xxxxxxxxxxxxxxx/wp-content/plugins/giphypress/js/giphypress_mce.js?wp-mce-4401-20160726
line:30
`

**Comment by pabloacastillo** [comment]
Ok, after more testing i found that the form is trying to do fetch two urls:

a) Fetch the forms from:
http://xxxxxxxxx/wp-json/ccf/v1/forms/?pages=1 

b) Try to fetch the form from:
http://xxxxxxxxx/wp-json/wp/v2/posts/3634

This last one fails since 3634 its not a post, its a ccf form so it fails to load with.
`
{
code: "rest_post_invalid_id",
message: "Invalid post id.",
data: {
status: 404
}
}
`

To test things  out, i disabled all my plugins and left only the "custom-contact-form" active and everything works, when i enable the "WP REST API" plugin it fails again.

Im using **Custom Contact Forms v7.8.3** and **WP REST API v2.0-beta13.1** on **Wordpress v4.6**


Thanks!

**Comment by pabloacastillo** [comment]
To force things, i changed the post type of 3364 from ccf_form to post.
The  http://xxxxxxxxx/wp-json/wp/v2/posts/3634 stops failing and now the chrome console replies with:
`
Uncaught TypeError: e.author.toJSON is not a function
source:http://xxxxxxxxx/wp-content/plugins/custom-contact-forms/assets/build/js/form-manager.min.js?ver=7.8.3
line:1
`

**Comment by pabloacastillo** [comment]
Ok, i did a rollback from **WP REST API v2.0-beta13.1** to **WP REST API v2.0-beta10** and everything works again.

**Comment by dellabravo** [comment]
+1 
Not working with WP REST API Version 2.0-beta13.1

**Comment by brianstateside** [comment]
temporal solution: I did **change** WP REST API Version 2.0 **from beta 13.1 to beta 10**. to get the CCF working.
looks like CCF is not adding support for the current WP rest api v2.  beta10 works.
